# Generated by Django 5.2.8 on 2025-11-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volatility_15m', models.FloatField()),
                ('ticks_15m', models.IntegerField()),
                ('ticks_5m', models.IntegerField()),
                ('vdelta_1m', models.FloatField()),
                ('vdelta_5m', models.FloatField()),
                ('volume_5m', models.FloatField()),
                ('volume_1h', models.FloatField()),
                ('oi_change_5m', models.FloatField()),
                ('oi_change_15m', models.FloatField()),
                ('oi_change_1h', models.FloatField()),
                ('funding_rate', models.FloatField(default=0.0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='screener.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', '-ts'], name='screener_sc_symbol__5a28d3_idx')],
            },
        ),
    ]
