# Generated by Django 5.2.8 on 2025-11-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_extend_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenersnapshot',
            name='vdelta_1m',
        ),
    ]
