# Generated by Django 5.2.8 on 2025-11-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_remove_screenersnapshot_vdelta_1m'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='market_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], default='futures', max_length=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_15m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_1h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_5m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='ticks_15m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='ticks_5m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_5m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volatility_15m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_1h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_5m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('symbol', 'market_type')},
        ),
    ]
