# Generated by Django 5.2.8 on 2025-11-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_symbol_market_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
