# Generated by Django 5.2.8 on 2025-11-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_verification_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='admin_approved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Заметки администратора о пользователе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
