# Generated by Django 5.2.8 on 2025-11-26 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screener', '0003_remove_screenersnapshot_vdelta_1m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('change_15m', 'Price change 15m, %'), ('change_1h', 'Price change 1h, %'), ('change_1d', 'Price change 1d, %'), ('oi_change_15m', 'OI change 15m, %'), ('oi_change_1h', 'OI change 1h, %'), ('volume_15m', 'Volume 15m'), ('volume_1h', 'Volume 1h'), ('funding_rate', 'Funding rate'), ('vdelta_15m', 'Vdelta 15m')], max_length=32)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<=')], max_length=2)),
                ('threshold', models.FloatField()),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Telegram chat id to send alerts to', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='screener.symbol')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
